apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: TopologyDomainProfile
        pluginConfig:
        - name: "DefaultEvictor"
        - name: "RemovePodsViolatingTopologyDomain"
          args:
            topologyKey: "huawei.com/topotree.domainid"
            npuResourceName: "huawei.com/Ascend910"
        plugins:
          deschedule:
            enabled:
              - "RemovePodsViolatingTopologyDomain"
